### ISSUE TITLE
[Design]: refactor: Make it easier to use

### ISSUE THREAD

**Issue by obiyankenobi** [HathorNetwork/hathor-wallet-lib#30]
Although the lib is functional, we've debated several improvements that can be done. It's still not easy for developers to start a new project, quickly add it and start interacting with Hathor's network. Right now, developers need some knowledge of the lib's inner workings to be able o use it.

We need a lib with a clear interface and classes for the different elements in Hathor-land: transactions, blocks, inputs, outputs, etc.

@msbrogli took a step on that direction when implementing the twitter bot (check wallet.js): https://github.com/HathorNetwork/twitter-hathor-bot

**Comment by pedroferreira1** [comment]
@obiyankenobi can you list here the first ideas you had when thinking about this refactor?

**Comment by obiyankenobi** [comment]
I wrote them in this document: https://docs.google.com/document/d/1tD7D07PvDHAbv2N0UqmDmSOO7WxE7dIAD2gyijIgjqw/edit

One of the problems has already been fixed. The other 2 are:
- hide lib internal state: nowadays, the dev still needs some knowledge about the lib's state and update it depending on the event it receives. 
- hide websocket class: we still do stuff like this `hathorLib.WebSocketHandler.on('reload_data', this.fetchDataFromServer);`

Both points are kind of addressed on the facade @msbrogli did, especially the second.

Regarding the first, I believe the lib should handle all state "under the hood", without interaction from the user.

**Comment by obiyankenobi** [comment]
One other thing is removing some data from storage that could be kept in memory, like `wallet:closed` flag.

**Comment by obiyankenobi** [comment]
Copying from #44 that was a duplicate issue:
"Create classes for each object type, so we would have a full description of their attributes and types."

**Comment by pedroferreira1** [comment]
We should also consider removing PIN/Password handling from the lib (maybe just let wallets use what we have now as default but allow it not to be required)

Comment: https://github.com/HathorNetwork/hathor-wallet-lib/pull/50#discussion_r373858260

**Comment by pedroferreira1** [comment]
> One other thing is removing some data from storage that could be kept in memory, like `wallet:closed` flag.

Some data could be kept in memory but we should take care when removing them from storage. The one from your example `wallet:closed` must be kept on storage because we use it after opening the app. We could do it with IPC_RENDERER messages to send data from electron main process to the renderer process but it was easier and more readable to do like this.

We just need to do this refactor carefully.

**Comment by msbrogli** [comment]
# Design for this issue

## Problem

Using the hathor-wallet-lib is not an easy task because the developer must understand its internal state and the correct order to call the internal methods.

## Solution

Develop clear and easy-to-use interfaces that allows developers to create wallets without diving deep into the internals of the library.

## Steps

I thought about the following steps to execute this refactor:

1. Define an initial interface for the classes that will be available in hathor-wallet-lib.
2. Refactor the Hathor Mobile Wallet to use this class, removing any other call to internal methods of the library.
3. Refactor the Hathor Desktop Wallet to use this class, removing any other call to internal methods of the library.
4. Refactor the internal methods of the hathor-wallet-lib without changing the interface of `HathorWallet`.

At the end of these steps, we will have a full refactor of the hathor-wallet-lib and both of our wallets will be migrated.

## Features

- It may be possible to create multiple wallets sharing a single connection.
- It may be possible to create read-only wallets using an xpub.
- The wallet may be initialized using either (i) a seed and a passphrase, (ii) an xpriv, (iii) an xpub, or (iv) a given list of addresses.
- Using PIN or Passwords to store sensitive data won't be handled by the library. We may at most provide some crypto methods.
- The wallet may decide whether it want to keep or discard the blocks and transactions.

## Classes

The following classes will be exposed by the hathor-wallet-lib at the end of the refactor:

- `HathorWallet`, which must receive both a storage and a connection.
- `Storage` (interface) and `MemoryStorage` (implementation).
- `Connection`, which handles all websocket connection stuff.
- `BaseTransaction`, `Transaction`, and `Block`, which will allow anyone to easily create, serialize, deserialize, and validate either a block or a transaction.
- `HathorAPI`, which will have methods to easily interact with our full node's API.

The idea is that we may create many wallets using `HathorWallet`, and they may share the same connection.

The storage cannot be shared between `HathorWallet` instances. Maybe we won't need a storage at all, but I'm still not sure about it. The ideia is that each wallet must decide how it will store its data, including the sensitive data.

These classes will communicate using events.

## Examples

### Basic use

```es6
const conn = new Connection("mainnet");
const xpub = "MY_XPUB_STRING";
const wallet = new HathorWallet({ conn, xpub });
wallet.on("ready", () => {
  console.log(`Connected to ${this.getNetwork()}`);
  console.log(`Current address: ${this.getCurrentAddress()}`);
  console.log(`Balance: ${this.getBalance()}`);
});
wallet.on("new-tx", (tx) => {
  const txBalance = wallet.getTxBalance(tx);  // { type: ["sent", "received"], amount, token: { uid, symbol } }
  if (wallet.isRegisteredToken(txBalance.token.uid) {
    console.log(`You ${txBalance.type} ${txBalance.amount} ${txBalance.token.symbol}. Current balance: ${this.getBalance()}`);
  } else {
    console.log(`[WARNING] New transaction from unregistered token.`);
  }
});
wallet.start()
```

### Not connected to a server

```es6
const conn = new Connection("mainnet");
const xpub = "MY_XPUB_STRING";
const wallet = new HathorWallet({ conn, xpub });

// You don't have to be connected to get a given address.
console.log(`Current address: ${wallet.getAddressByPath("/1'/0")}`);
```

### Many wallets sharing one connection

```es6
const conn = new Connection("mainnet");

const xpub = "MY_XPUB_STRING";
const wallet1 = new HathorWallet({ conn, xpub });
wallet1.id = "Wallet 1";

const xpriv = "MY_XPRIV_STRING";
const wallet2 = new HathorWallet({ conn, xpriv });
wallet2.id = "Wallet 2";

// Both the seed and the passphrase won't be stored. The wallet
// will store only the xpriv generated from them.
const seed = "MY_SEED_WORDS";
const passphrase = "MY_PASSPHRASE";
const wallet3 = new HathorWallet({ conn, seed, passphrase });
wallet3.id = "Wallet 3";

const onReady = () => {
  console.log(`[${this.id}] Connected to ${this.getNetwork()}`);
  console.log(`[${this.id}] Current address: ${this.getCurrentAddress()}`);
  console.log(`[${this.id}] Balance: ${this.getBalance()}`);
  this.stop();
};

const onClosed = () => {
  console.log("[Wallet 1] Disconnected.");
};

wallet1.on("ready", onReady);
wallet2.on("ready", onReady);
wallet3.on("ready", onReady);

wallet1.on("closed", onClosed);
wallet2.on("closed", onClosed);
wallet3.on("closed", onClosed);

// The first call to start will open the connection, while the last call to
// stop will close the connection.
wallet1.start();
wallet2.start();
wallet3.start();
```

**Comment by msbrogli** [comment]
@pedroferreira1 @obiyankenobi @jansegre Can you review the design, please?

**Comment by obiyankenobi** [comment]
The design looks great, very thorough! Some quick points:

- we probably also need classes for TokenCreationTransaction and MergedMiningBlock;
- you mention the input selection algo. I think this task should not be a part of the wallet refactor;
- we'd fire 2 events on wallet state change? One for the specific event and another for the general case (`update-state `)?

Now some more 'philosophical' decisions:

1) I'm trying to understand the advantage of registering tokens on the lib.  I'm not sure this should be under the lib's responsibility. The example using this "feature" of the lib is pretty simple:
```js
wallet.on("new-tx", (tx) => {
  const txBalance = wallet.getTxBalance(tx);  // { type: ["sent", "received"], amount, token: { uid, symbol } }
  if (wallet.isRegisteredToken(txBalance.token.uid) {
    console.log(`You ${txBalance.type} ${txBalance.amount} ${txBalance.token.symbol}. Current balance: ${this.getBalance()}`);
  } else {
    console.log(`[WARNING] New transaction from unregistered token.`);
  }
});
```
It'd be trivial in this case for the developer do this same check, just by having the list of his registered tokens. I'm trying to think of more complex use cases, where this would be useful.

2) Which data should be stored on the lib. For me, this is a very sensitive point to discuss. Will the lib store the history of transactions? If we want to have `wallet. getTxHistory()`, it definitely has to store it. On the other hand, we could only notify the wallet about new/updated txs and let it handle the updates it needs to do on balance, etc.
> The wallet may decide whether it want to keep or discard the blocks and transactions.

I'm not sure I understand this sentence. What would it discard? We don't want the wallet to interfere with the lib's internal state/storage.

**Comment by msbrogli** [comment]
@obiyankenobi 

> * we probably also need classes for TokenCreationTransaction and MergedMiningBlock;

I just updated the design and included both the TokenCreationTransaction and the MergedMiningBlock.

> * you mention the input selection algo. I think this task should not be a part of the wallet refactor;

We don't have to fully implement this interface. So, in this case, we can add this option later.

> * we'd fire 2 events on wallet state change? One for the specific event and another for the general case (`update-state `)?

Yes, I think it is easier for the developers. I like pieces of code like `wallet.on("ready", ...)`, `wallet.on("connecting", ...)`, and so on. But, if they just want to update the state of the wallet in the UI, they can simply do `wallet.on("update-state", ...)`. What do you think?

> 1. I'm trying to understand the advantage of registering tokens on the lib.  I'm not sure this should be under the lib's responsibility. The example using this "feature" of the lib is pretty simple:
> 
> ```js
> wallet.on("new-tx", (tx) => {
>   const txBalance = wallet.getTxBalance(tx);  // { type: ["sent", "received"], amount, token: { uid, symbol } }
>   if (wallet.isRegisteredToken(txBalance.token.uid) {
>     console.log(`You ${txBalance.type} ${txBalance.amount} ${txBalance.token.symbol}. Current balance: ${this.getBalance()}`);
>   } else {
>     console.log(`[WARNING] New transaction from unregistered token.`);
>   }
> });
> ```
> 
> It'd be trivial in this case for the developer do this same check, just by having the list of his registered tokens. I'm trying to think of more complex use cases, where this would be useful.

I agree. Maybe we can leave it out of `HathorWallet`. I'm only concerned whether developers are aware of the risks when using other tokens. But I agree that it is easily done somewhere else.
 
> 1. Which data should be stored on the lib. For me, this is a very sensitive point to discuss. Will the lib store the history of transactions? If we want to have `wallet. getTxHistory()`, it definitely has to store it. On the other hand, we could only notify the wallet about new/updated txs and let it handle the updates it needs to do on balance, etc.

Maybe we can have a `TxLarder` (TxStore? Tx (not related to the `Storage`) that receives a wallet, listen for the events and store the transactions and keep the balances updated. It may be automatically instantiated inside the wallet or given as a parameter in the constructor. This object will have both the `getBalance(...)` and `getTxHistory(...)` methods.

We still have to discuss where the UTXOs will be stored. They are only required for the `prepareTransaction(...)` method.

Developers would be able to disable it by passing a `disableTxLarder: true` in the constructor of the wallet. Something like this:

```es6
const wallet = new Wallet({ conn, seed, disableTxLarder: true });
```

> > The wallet may decide whether it want to keep or discard the blocks and transactions.
> 
> I'm not sure I understand this sentence. What would it discard? We don't want the wallet to interfere with the lib's internal state/storage.

I meant that some wallets may not care about the history itself. So, they should be able to discard the tx history to save some memory. Maybe the `TxLarder` idea can do it easily.

**Comment by obiyankenobi** [comment]
> Yes, I think it is easier for the developers. I like pieces of code like `wallet.on("ready", ...)`, `wallet.on("connecting", ...)`, and so on. But, if they just want to update the state of the wallet in the UI, they can simply do `wallet.on("update-state", ...)`. What do you think?

I agree, we can keep both.

> Maybe we can have a TxLarder (TxStore? Tx (not related to the Storage) that receives a wallet, listen for the events and store the transactions and keep the balances updated. It may be automatically instantiated inside the wallet or given as a parameter in the constructor. This object will have both the getBalance(...) and getTxHistory(...) methods.

I'm not sure I understand this idea. If we don't save the txs, we cannot have the balance/history and `prepareTransaction()`, right? In that case, we'd use the lib only to receive txs in realtime, which might be what some people actually want. In that case, we could have a parameter `lightMode` when starting the wallet, so it won't save this information. Is this the same as `disableTxLarder`?

**Comment by msbrogli** [comment]
It would be similar. We could have different types of larder. One that stores the full history, another one that only updates the balance, and so on. I'm not sure what types we would really have, but it would separate the storage from the wallet itself.

**Comment by obiyankenobi** [comment]
I don't think we can not store the full history and have even simple things as the balance. We may receive duplicate txs, have some txs voided, etc. We need to check on the history to update the balance correctly. So I think we either store the full history (and have all the functionality) or we don't store anything.

But I'm not 100% sure about this. I guess we can find it out when we start coding. The first version could store everything and we try making 'lighter' storages later.

**Comment by pedroferreira1** [comment]
I agree with @obiyankenobi about the token registering, I think each application should handle it the way it wants. My only concern is about our two wallets (desktop and mobile). We currently use some methods (like `addToken`) from the lib to handle the registering, to prevent duplicating the code in both repositories. We probably have some other cases like this, where we don't need the lib to handle some situation but it was interesting to have it on the lib to use in both repositories. What should we do here? Create another repository like a `hathor-common`? Duplicate the code? The `hathor-common` repository could also help prevent duplicating react components between the wallet and the explorer.

Another thing, even though I think we shouldn't handle token registering in the lib, I believe we should have some methods to work with tokens. Like `getTokenData`, that gets token name/symbol from the full node to check if is correct, `configStringToData`, `dataToConfigString`.

Changing topics, keeping the full tx history is not necessary even for sending tokens, we could store only the utxos, which would reduce the data stored. We should think about this because of the problem we had on the wallet using `localStorage`. If someone decides to create an application using `localStorage` we shouldn't be saving lots of unnecessary data.

About the events emitted by the wallet, we should also consider the `height_updated` event that we have nowadays.

At last, I am thinking if it's worth it to have Input/Output classes. Nowadays we have some methods that we could use them, like `output.isMine`, `output.isLocked`, `input.getSignature(dataToSign)`. I think we should do it.

**Comment by obiyankenobi** [comment]
From what I've seen, `addToken` only saves the token name, symbol and uid in the storage, so I don't think it should be in the lib.

I also agree about classes for inputs and outputs.

**Comment by pedroferreira1** [comment]
> From what I've seen, addToken only saves the token name, symbol and uid in the storage, so I don't think it should be in the lib.

Yes, that's exactly what I said, I agree with you. I just think we should do something so we don't duplicate this code to use in both wallet desktop and mobile.

**Comment by jansegre** [comment]
This design looks good. I don't know if we have done this, but it wouldn't hurt to take a peek at how others are doing this (for instance: https://github.com/bitpay/bitcore/tree/master/packages/bitcore-wallet-service).

**Comment by obiyankenobi** [comment]
One other thing really important is about the errors, as we have #22 open. Nowadays, we've been using objects with property `success` in certain lib functions. For example, in `wallet.prepareSendTokensData` we have:
```
if (outputsAmount === 0) {
  return {success: false, message:  `Token: ${token.symbol}. Total value can't be 0`};
}
```

I believe it would be better to always throw an error in this case, extending from a base error class.

**Comment by pedroferreira1** [comment]
Another thing I thought today is that it would be good to have an easy way to override some constants. For instance, imagine a use case where the user needs to generate more than 20 addresses even before receiving a transaction.

So it would be good to have a way to increase the `GAP_LIMIT` constant from the apps that uses the lib.

**Comment by msbrogli** [comment]
> One other thing really important is about the errors, as we have #22 open. Nowadays, we've been using objects with property `success` in certain lib functions. For example, in `wallet.prepareSendTokensData` we have:
> 
> ```
> if (outputsAmount === 0) {
>   return {success: false, message:  `Token: ${token.symbol}. Total value can't be 0`};
> }
> ```
> 
> I believe it would be better to always throw an error in this case, extending from a base error class.

I agree.

**Comment by msbrogli** [comment]
I updated the design with yours comments.

**Comment by obiyankenobi** [comment]
The design seems really good to me. The only item that is unclear is `TxLarder`. It's still unclear to me how it would work and even if it should be in the lib. As I commented before:
> I saw that you also added TxLarder as a class that would be exposed by the lib. It doesn't seem something that we should do. It'd would require some internal knowledge about the lib, which is one of the things we want to change in this refactor.

Anyways, I think that regarding this storage area it's ok if we get more answers when we actually start implementing the changes, so I'm ok considering this finished right now.

**Comment by pedroferreira1** [comment]
@msbrogli Approved
